lenguaje: node_js
cache:
  directories:
  - node_modules
  - "~/.npm"
node_js:
- '14'
git:
  depth: 3
script:
- yarn test
deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  github_token: "$GITHUB_TOKEN"
  api_key:
    secure: g+0u8eFVULvTr4FEAmkj92O6E9IgLFNHcuoPKC6RjZdbVB57kVkrm7+egB7HtaSfeZ+1a/eJ2FEZacGu6syfofEGwxnYjwqL9TuPiVydu85h6wZbcKV7VR6cPf4649C8lRQv2MoxSTpNMBxekjRX29lWrV0/Cyr9UL+24dz2g+WKUHsKZk2N61NFllmzFd2rOslBUJ8zU33VfckmQYwrAL4mPuPSZ7Z5r03zxbq9kwnrp4HVrgxPWwykD6ffuthLiHJVUcFl0eiOpc40M2oZpAhpvDKVxPYsvFm7F9LCsmPv/6cKU3QvlooaTX17y0DFml1XS19jwcIlUVDRULJVQ94uPWGZTgETGh5QGRnIufIGqlbf0pg/y2EFyvVGsWUjcCBimJe3E26Gr8MMbNsONvP8xL97PGhJ8+D37xTmZKDCrE/nL6+t3Eg7IIhZY44eNe6gGJSGPL37q3xSwlhYWFScO5gSNEU5/Kd1Ke/jviDxuQQ4Q44iQ2QCPDhqFWRxk13daRcYF2cP2tG6/SbBgo06Z/kvbyX7Al1CP4wCnkyaUbKjr7ywlFfHoLeaV2y/gQMH8SiuGYmW3KzGhTkDbHAP6pZzzWHYtqb4fHLz2GYxxFGbS82/xSEYDFeKP9Q5GvCrkV+vdJequ2/+mT4EiXQUYrSgOKwKuq6CKs/0Sug=
  app: portfolio-backend-krlosaren
  on:
    repo: KrlosAren/krlosaren.backend
