lenguaje: node_js
cache:
  directories:
  - node_modules
  - "~/.npm"
node_js:
- '14'
git:
  depth: 3
script:
- yarn test
deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  github_token: "$GITHUB_TOKEN"
  api_key:
    secure: IvQ2uMbXJS6ukvAY+tbt7WOAdpv0BA8OJG6TAeKiSzYpIB9YcAgUWxdjCpV0yNtsQZS1dMoye8tBsVehyQhm8Sy5c+d8FysEGd43wzwfPb6sosjohnCdjP6z02zSrOPKaZPr9FIbmEWokmCKmBjXtdQNXbBwDCpex2rlf9kV/aB4gDkMiGA8dD+aWZPanjQgPXG4Vnt60Lj82vjLMwshS5dRBgrc3reiuduz+XsJOZFnlmMmd+rVlgB11+Vu47OfTQLdpQ9SvkoAvD7/5N88xFN/1ZKz2+MDM1QNMsAyWFnjJDENR4/v4R/lkcEVhTvQmH7MpmhmCs0ukq7zoQkg7wfY0doyXfKzS7VkRTn8PNr6GzV4uqv8ftwqV2VXmH/VQ7R8+rfa04n4BSHwID9dxTvDvzxsOOrD4FEiKbiffG5CzhkgrWVL1aJUztKk2A7MdFZ2K7e694RPaqPll+OP2KzErg2cRI+KUq8gb2svWNdYTUWKls+uyXL106xt8TWnMJs3iDYuz1Gk0uEs9+gDopKG9qepxM2TSUwnaUcYddlieIspxSyci4s+b+eXZmdwFeTFj3/LO8nA22sjCBXHIOm5w+yeagQHwx7msox+TeLCNX0mIowlyjp96ZHt2jWJtuU/9ppQRROdEtopsIQYHw+AzJHBdkuvULt/IeUxN/Y=
  app: portfolio-backend-krlosaren
  on:
    repo: KrlosAren/krlosaren.backend
