lenguaje: node_js
cache:
  directories:
  - node_modules
  - "~/.npm"
node_js:
- '14'
git:
  depth: 3
script:
- yarn test
deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  github_token: "$GITHUB_TOKEN"
  api_key:
    secure: ZQ/LNU4m+z4IM+Q/T0rpc0hfsJHbgxJxjZownkyzcC/z+kSopOQIJYSgTXljKMf21maqXbHlSnvhFOPz8rHHavXhlrbh/L9epu+TlmHGs1JoPLNNdd5c9dAegnRZsy9WsofOmgMc0fR2q4D2JtAQWpfVirUDmuRKEZldH8gMhiBkOJ6CklTjK0yUQndqMBAzqT97lgd8MMpexFm7iHPIKhxr6LB2GJ0y5NPOXYIbIkZuoNz8yu4mWThypacSqMSd0jSSkz8+Nw5BXt9glmZC/yfUTJEETpZYuKRSYB9FFtlkH/tHfULkuj5cUugsp05mcls0oE7MNPes9BCe8zVw67qURbazkzA1xN/7BSpnwYOiu/q17gXzYceZdpSFj/Opkl6l64ygAiSjOjIqKnQGrRWa1Fm/h7VqJ6O/lBZaOhNoEX6GIFfMTryaXIzUkcUUD9sXkEU7mR3TGg8lsYWEbr1FD/CnUNxS09f4ggzgLHqyAnyMWhrJc9hbXKahwkCrSwIowuzDkordFZIU8yLHLSnIgaWmvxhWqGAKfuEYKCOGJew3GRhVQJ7YpFYOoZTdeKoDjnvq7MZRsDFPy6016ObOleIoOdyQlnC/SIZc8A+9j3S6LF2Flt1D/7hdzH5OWtzO+7WreE49svPVAUrVSq1OqN7X/g66auqhYCPsONU=
  app: krlosaren-backend
  on:
    repo: KrlosAren/krlosaren.backend
