lenguaje: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '14'
git:
  depth: 3
script:
  - yarn test
deploy:
  github_token: $GITHUB_TOKEN
  provider: heroku
  api_key: 58b62f1a-2c6c-4c10-bed0-d47aa2a7deba
  app: krlosaren.backend
  on:
    repo: KrlosAren/krlosaren.backend
  skip_cleanup: true
  keep-history: true

