lenguaje: node_js
cache:
  directories:
  - node_modules
  - "~/.npm"
node_js:
- '14'
git:
  depth: 3
script:
- yarn test
deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  github_token: "$GITHUB_TOKEN"
  api_key:
    secure: STHmJ7sQW4NETtXCPCrX+sxAc9eZ1+9fyIU9p1ZA3UkQDZeICtmTtVxwG/dBlwrkGW/tloyMo/2uJc2XnFb2jVdixf1SK7Xl6D/YxuYsH7Zvp277XaSR/0Kz3PKRxUooFMnefy+CCz/60jdYy0gqp8wpeWzGrgwd4GfKc50uj/F3TOWPhewh7cPuc18P9U2uLjjQ3OQESR2lUNAY4ziWbALVM80BQfbW+x1ksXBoryod9LndYB7NfYGOMJUIyqixgISqomkp1rVzO+Pl0m+q2WbiZPc8LDCojj6vLfMAqBLrqIKZ7RjUTtp+aG+J2HCgQ0E/PVCnOCuls6PoxLyWkXubWzm0NFNiVmar4KbmovwpmhiAx2NCjs/4D2K1YQ0HKhEGJ0wPaMZEK4VavUMKweRJAFx473RU6LPAxuTe6kybmHtY152QOjHjBs/MZFqAFS2B+dN96VcrX1jHo77u021iuAZDY+jpXRm/G9OtzQvZEhdCZVn3Dhns69CSBMhBM2T4CLqEZQMAtsci/mFzCwmk0i+YOroF+5uJ+5mVLkUV+d/ISgYOoT4DfYmCIKUQWXk3kRvL5ehTfeNGjRp2ow3Big4IssEPseiLJd4EwCGZXi/FYXwJyKius9ayugjJp9Cxq9Hk492WtpAhW2o/uk8wRR8hf01RhsyUyl5VzCQ=
  app: portfolio-backend-krlosaren
  on:
    repo: KrlosAren/krlosaren.backend
